/* =============================================
   MAPAPOLO 2026 - Datos del Directorio
   Empresas reales del Polo Nacional de Contenidos Digitales
   ============================================= */

// Espacios físicos del Polo Digital (mapa de zonas)
const ESPACIOS = {
    // ====== PLANTA BAJA ======
    'recepcion': {
        id: 'recepcion',
        nombre: 'Recepción / Hall',
        planta: 'baja',
        tipo: 'comun',
        icono: 'door-open',
        descripcion: 'Acceso principal del edificio E3 del complejo Tabacalera. Punto de bienvenida e información al visitante.',
        servicios: ['Atención al visitante', 'Información general', 'Pantalla digital'],
    },
    'agora': {
        id: 'agora',
        nombre: 'Ágora',
        planta: 'baja',
        tipo: 'comun',
        icono: 'theater',
        descripcion: 'Espacio central abierto para ponencias, pitchs, competiciones de esports y demo-days.',
        servicios: ['Escenario', 'Grada', 'Pantalla LED'],
        capacidad: '120 personas',
    },
    'patio-1': {
        id: 'patio-1',
        nombre: 'Patio 1',
        planta: 'baja',
        tipo: 'comun',
        icono: 'sun',
        descripcion: 'Patio principal con luz natural, ideal para eventos, networking y presentaciones al aire libre.',
        servicios: ['Equipo audiovisual', 'Pantallas laterales 65"', 'Pantalla de fondo 3,2x3 m'],
    },
    'showroom': {
        id: 'showroom',
        nombre: 'Showroom',
        planta: 'baja',
        tipo: 'comun',
        icono: 'eye',
        descripcion: 'Espacio expositivo donde las empresas muestran sus productos y proyectos.',
        servicios: ['Vitrinas', 'Iluminación profesional'],
    },
    'aula-1': {
        id: 'aula-1',
        nombre: 'Aula de Formación 1',
        planta: 'baja',
        tipo: 'aula',
        icono: 'book',
        descripcion: 'Aula equipada para capacitación técnica y workshops especializados.',
        capacidad: '24 personas',
    },
    'aula-2': {
        id: 'aula-2',
        nombre: 'Aula de Formación 2',
        planta: 'baja',
        tipo: 'aula',
        icono: 'book',
        descripcion: 'Aula multiusos para formación y eventos formativos del sector.',
        capacidad: '24 personas',
    },
    'aula-3': {
        id: 'aula-3',
        nombre: 'Aula de Formación 3',
        planta: 'baja',
        tipo: 'aula',
        icono: 'book',
        descripcion: 'Aula multiusos para formación y eventos formativos del sector.',
        capacidad: '24 personas',
    },
    'aula-4': {
        id: 'aula-4',
        nombre: 'Aula de Formación 4',
        planta: 'baja',
        tipo: 'aula',
        icono: 'book',
        descripcion: 'Aula gestionada por la UMA para cátedras de tecnología de contenidos digitales.',
        capacidad: '24 personas',
    },
    'aula-5': {
        id: 'aula-5',
        nombre: 'Aula de Formación 5',
        planta: 'baja',
        tipo: 'aula',
        icono: 'book',
        descripcion: 'Aula multiusos para talleres y formación específica.',
        capacidad: '24 personas',
    },
    'aula-6': {
        id: 'aula-6',
        nombre: 'Aula de Formación 6',
        planta: 'baja',
        tipo: 'aula',
        icono: 'book',
        descripcion: 'Aula con ordenadores para formación técnica avanzada.',
        capacidad: '48 personas',
    },
    'oficina-promalaga': {
        id: 'oficina-promalaga',
        nombre: 'Oficina Promálaga',
        planta: 'baja',
        tipo: 'institucion',
        icono: 'building',
        descripcion: 'Oficina de Promálaga, entidad gestora del Polo. Ofrece asesoramiento a emprendedores.',
    },
    'uma': {
        id: 'uma',
        nombre: 'Universidad de Málaga (UMA)',
        planta: 'baja',
        tipo: 'institucion',
        icono: 'graduation',
        descripcion: 'Espacio de la UMA dedicado a cátedras de investigación en contenidos digitales y nuevas tecnologías.',
    },
    'modulo-1': {
        id: 'modulo-1',
        nombre: 'Módulo de Empresas 1',
        planta: 'baja',
        tipo: 'oficinas',
        icono: 'briefcase',
        descripcion: 'Módulo de oficinas para empresas consolidadas del sector.',
    },
    'modulo-2': {
        id: 'modulo-2',
        nombre: 'Módulo de Empresas 2',
        planta: 'baja',
        tipo: 'oficinas',
        icono: 'briefcase',
        descripcion: 'Módulo de oficinas para empresas consolidadas del sector.',
    },
    'coworking-1': {
        id: 'coworking-1',
        nombre: 'Coworking 1 (CW1)',
        planta: 'baja',
        tipo: 'coworking',
        icono: 'users',
        descripcion: 'Zona de coworking con puestos individuales y grupales para startups y proyectos.',
    },
    'coworking-2': {
        id: 'coworking-2',
        nombre: 'Coworking 2 (CW2)',
        planta: 'baja',
        tipo: 'coworking',
        icono: 'users',
        descripcion: 'Segunda zona de coworking con puestos para equipos de trabajo emergentes.',
    },

    // ====== PLANTA PRIMERA ======
    'go2work': {
        id: 'go2work',
        nombre: 'Go2Work (Coworking Premium)',
        planta: 'primera',
        tipo: 'coworking',
        icono: 'rocket',
        descripcion: 'Espacio de coworking de alto rendimiento para startups en fase semilla y empresas emergentes.',
        servicios: ['Puestos ergonómicos', 'Salas de reunión', 'Zona chill-out'],
    },
    'despacho-3': {
        id: 'despacho-3',
        nombre: 'Despacho 3',
        planta: 'primera',
        tipo: 'oficinas',
        icono: 'door-closed',
        descripcion: 'Despacho privado para empresas en crecimiento.',
    },
    'despacho-4': {
        id: 'despacho-4',
        nombre: 'Despacho 4',
        planta: 'primera',
        tipo: 'oficinas',
        icono: 'door-closed',
        descripcion: 'Despacho privado para estudios y productoras.',
    },
    'despacho-flex': {
        id: 'despacho-flex',
        nombre: 'Flexworking',
        planta: 'primera',
        tipo: 'coworking',
        icono: 'shuffle',
        descripcion: 'Espacio de trabajo flexible con escritorios compartidos.',
    },
    'despacho-1': {
        id: 'despacho-1',
        nombre: 'Despacho 1',
        planta: 'primera',
        tipo: 'oficinas',
        icono: 'door-closed',
        descripcion: 'Despacho privado para empresa incubada.',
    },
    'despacho-2': {
        id: 'despacho-2',
        nombre: 'Despacho 2',
        planta: 'primera',
        tipo: 'oficinas',
        icono: 'door-closed',
        descripcion: 'Despacho privado para empresa incubada.',
    },
    'lab-vr': {
        id: 'lab-vr',
        nombre: 'Laboratorio VR / XR',
        planta: 'primera',
        tipo: 'laboratorio',
        icono: 'vr',
        descripcion: 'Laboratorio equipado con dispositivos de última generación (Apple Vision Pro, Meta Quest 3) para el desarrollo y prueba de experiencias inmersivas.',
        equipamiento: ['Apple Vision Pro', 'Meta Quest 3', 'HTC Vive Pro', 'Estación de captura volumétrica'],
    },
    'lab-audio': {
        id: 'lab-audio',
        nombre: 'Estudio de Grabación de Audio',
        planta: 'primera',
        tipo: 'laboratorio',
        icono: 'mic',
        descripcion: 'Estudio acústicamente aislado con equipamiento profesional para grabación, mezcla y masterización.',
        equipamiento: ['Cabina insonorizada', 'Micrófonos profesionales', 'Mesa de mezclas', 'Software Pro Tools'],
    },
    'lab-video': {
        id: 'lab-video',
        nombre: 'Sala Audiovisual',
        planta: 'primera',
        tipo: 'laboratorio',
        icono: 'video',
        descripcion: 'Espacio con cámaras 8K, equipo de iluminación y croma para producción audiovisual profesional.',
        equipamiento: ['Cámaras 8K', 'Croma y fondos', 'Iluminación profesional', 'Estación de edición 4K'],
    },
    'lab-3d': {
        id: 'lab-3d',
        nombre: 'Laboratorio de Impresión 3D',
        planta: 'primera',
        tipo: 'laboratorio',
        icono: 'printer',
        descripcion: 'Laboratorio con casi una veintena de impresoras 3D, escáneres y cortadora láser para prototipado rápido.',
        equipamiento: ['Impresoras FDM', 'Impresoras de resina', 'Escáneres 3D', 'Cortadora láser', 'Software de modelado'],
    },
    'sala-proyeccion': {
        id: 'sala-proyeccion',
        nombre: 'Sala de Proyección',
        planta: 'primera',
        tipo: 'aula',
        icono: 'film',
        descripcion: 'Sala con proyector y pantalla para proyecciones, presentaciones y eventos audiovisuales.',
        capacidad: '50 personas',
    },
    'sala-reuniones-1': {
        id: 'sala-reuniones-1',
        nombre: 'Sala 4.1',
        planta: 'baja',
        tipo: 'comun',
        icono: 'handshake',
        descripcion: 'Sala de reuniones para 5 personas con equipamiento audiovisual.',
        capacidad: '5 personas',
    },
    'sala-reuniones-2': {
        id: 'sala-reuniones-2',
        nombre: 'Sala 4.2',
        planta: 'baja',
        tipo: 'comun',
        icono: 'handshake',
        descripcion: 'Sala de reuniones para 5 personas con equipamiento audiovisual.',
        capacidad: '5 personas',
    },
    'agora-2': {
        id: 'agora-2',
        nombre: 'Ágora 2',
        planta: 'baja',
        tipo: 'comun',
        icono: 'theater',
        descripcion: 'Sala versátil para reuniones, formaciones pequeñas y workshops.',
        capacidad: '10 personas',
    },
};

// Empresas reales del Polo (extraídas de polodigital.eu/habitantes)
const EMPRESAS = [
    {
        id: '64train',
        nombre: '64Train',
        web: 'https://www.64train.com',
        sector: 'videojuegos',
        sectorLabel: 'Videojuegos',
        tecnologias: ['Unity', 'C#', 'Game Design', 'Indie Games'],
        descripcion: 'Estudio independiente de desarrollo de videojuegos especializado en experiencias narrativas y diseño de juego innovador.',
        espacioId: 'go2work',
        tamano: 'pyme',
        empleados: 8,
    },
    {
        id: 'ademass',
        nombre: 'Ademass',
        web: 'https://ademass.com',
        sector: 'marketing',
        sectorLabel: 'Marketing Digital',
        tecnologias: ['Performance Marketing', 'SEO', 'Analytics', 'Social Media'],
        descripcion: 'Agencia de marketing digital especializada en campañas de rendimiento para empresas del sector tecnológico.',
        espacioId: 'modulo-1',
        tamano: 'pyme',
        empleados: 12,
    },
    {
        id: 'bebite',
        nombre: 'Bebite',
        web: 'https://bebyte.net',
        sector: 'ciberseguridad',
        sectorLabel: 'Ciberseguridad',
        tecnologias: ['Pentesting', 'Security Audits', 'GDPR', 'Ethical Hacking'],
        descripcion: 'Empresa de ciberseguridad que ofrece servicios de auditoría, pentesting y consultoría de seguridad informática.',
        espacioId: 'modulo-1',
        tamano: 'startup',
        empleados: 5,
    },
    {
        id: 'bestridesimulators',
        nombre: 'Best Ride Simulators',
        web: 'https://bestridesimulators.com',
        sector: 'simulacion',
        sectorLabel: 'Simulación',
        tecnologias: ['Unreal Engine', 'Motion Simulation', 'Haptics', '3D Realism'],
        descripcion: 'Desarrolladores de simuladores de movimiento para entrenamiento, entretenimiento y realidad virtual de alta fidelidad.',
        espacioId: 'despacho-flex',
        tamano: 'pyme',
        empleados: 10,
    },
    {
        id: 'cienciavr',
        nombre: 'CienciaVR',
        web: 'https://cienciavr.com',
        sector: 'xr',
        sectorLabel: 'Realidad Virtual / XR',
        tecnologias: ['VR', 'Educación', 'Unity', 'C#'],
        descripcion: 'Creación de experiencias de realidad virtual aplicadas a la educación y divulgación científica.',
        espacioId: 'go2work',
        tamano: 'startup',
        empleados: 6,
    },
    {
        id: 'cookingandpublishing',
        nombre: 'Cooking & Publishing',
        web: 'https://www.cookingandpublishing.com',
        sector: 'edicion',
        sectorLabel: 'Edición y Contenido',
        tecnologias: ['Editorial Digital', 'Contenidos', 'Marketing de Contenidos'],
        descripcion: 'Editorial digital especializada en contenidos gastronómicos y publicación de libros interactivos.',
        espacioId: 'coworking-1',
        tamano: 'startup',
        empleados: 4,
    },
    {
        id: 'eartes',
        nombre: 'Eartes',
        web: 'https://www.eartes.com',
        sector: 'arte-digital',
        sectorLabel: 'Arte Digital',
        tecnologias: ['Ilustración Digital', 'Diseño', 'NFT', 'Animación 2D'],
        descripcion: 'Estudio de ilustración digital y diseño creativo especializado en arte conceptual para producciones.',
        espacioId: 'despacho-3',
        tamano: 'freelance',
        empleados: 2,
    },
    {
        id: 'featlander',
        nombre: 'Featlander',
        web: 'https://featlander.com',
        sector: 'videojuegos',
        sectorLabel: 'Videojuegos',
        tecnologias: ['Unity', 'Mobile Games', 'Hyper-casual', 'Game Design'],
        descripcion: 'Estudio de videojuegos móviles especializados en juegos hiper-casuales con mecánicas adictivas.',
        espacioId: 'go2work',
        tamano: 'startup',
        empleados: 7,
    },
    {
        id: 'forgottenempires',
        nombre: 'Forgotten Empires',
        web: 'https://www.forgottenempires.net',
        sector: 'videojuegos',
        sectorLabel: 'Videojuegos',
        tecnologias: ['Unreal Engine', 'Strategy Games', 'Age of Empires', 'RTS'],
        descripcion: 'Estudio de reconocido prestigio internacional, desarrollador de títulos como Age of Empires y Age of Mythology.',
        espacioId: 'modulo-2',
        tamano: 'gran-empresa',
        empleados: 65,
    },
    {
        id: 'gimnasioescenico',
        nombre: 'Gimnasio Escénico',
        web: 'https://gimnasioescenico.com',
        sector: 'artes-escenicas',
        sectorLabel: 'Artes Escénicas',
        tecnologias: ['Motion Capture', 'Performing Arts', 'Realidad Virtual', 'Teatro Inmersivo'],
        descripcion: 'Compañía que fusiona artes escénicas con tecnología, creando experiencias inmersivas de teatro en VR.',
        espacioId: 'coworking-2',
        tamano: 'pyme',
        empleados: 9,
    },
    {
        id: 'heqate',
        nombre: 'Heqate',
        web: 'https://heqate.com',
        sector: 'produccion-audiovisual',
        sectorLabel: 'Producción Audiovisual',
        tecnologias: ['Producción Video', 'Post-producción', 'Color Grading', 'Motion Graphics'],
        descripcion: 'Productora audiovisual especializada en contenido de marca, documentales y post-producción de alta calidad.',
        espacioId: 'despacho-4',
        tamano: 'pyme',
        empleados: 8,
    },
    {
        id: 'inakin',
        nombre: 'Inakin Studios',
        web: 'https://twitter.com/Inakin',
        sector: 'videojuegos',
        sectorLabel: 'Videojuegos',
        tecnologias: ['Unreal Engine', 'Action Games', 'Multiplayer', '3D Art'],
        descripcion: 'Estudio indie centrado en el desarrollo de juegos de acción con mecánicas multijugador innovadoras.',
        espacioId: 'go2work',
        tamano: 'startup',
        empleados: 5,
    },
    {
        id: 'inone',
        nombre: 'Inone',
        web: 'https://www.inone.es',
        sector: 'ia',
        sectorLabel: 'Inteligencia Artificial',
        tecnologias: ['Machine Learning', 'NLP', 'Computer Vision', 'LLMs'],
        descripcion: 'Consultora tecnológica especializada en soluciones de inteligencia artificial y machine learning para empresas.',
        espacioId: 'modulo-2',
        tamano: 'pyme',
        empleados: 15,
    },
    {
        id: 'krilloud',
        nombre: 'Krilloud',
        web: 'https://krilloud.com',
        sector: 'audio',
        sectorLabel: 'Audio y Sonido',
        tecnologias: ['Sound Design', 'Audio Interactivo', 'Middleware Audio', 'FMOD'],
        descripcion: 'Estudio de diseño de sonido y audio interactivo para videojuegos, apps y experiencias inmersivas.',
        espacioId: 'lab-audio',
        tamano: 'startup',
        empleados: 4,
    },
    {
        id: 'malagafilmoffice',
        nombre: 'Málaga Film Office',
        web: 'https://www.malagafilmoffice.com',
        sector: 'produccion-audiovisual',
        sectorLabel: 'Producción Audiovisual',
        tecnologias: ['Producción', 'Localización', 'Networking Industria', 'Asesoramiento'],
        descripcion: 'Oficina de apoyo a rodajes de Málaga. Punto de referencia para productoras nacionales e internacionales.',
        espacioId: 'despacho-4',
        tamano: 'institucion',
        empleados: 6,
    },
    {
        id: 'mickrea',
        nombre: 'Mickrea',
        web: 'https://mickrea.com',
        sector: 'xr',
        sectorLabel: 'Realidad Mixta',
        tecnologias: ['Mixed Reality', 'HoloLens', 'Spatial Computing', 'Industrial XR'],
        descripcion: 'Estudio pionero en realidad mixta aplicada a industria, formación y experiencias inmersivas B2B.',
        espacioId: 'lab-vr',
        tamano: 'startup',
        empleados: 5,
    },
    {
        id: 'pablobecerra',
        nombre: 'Pablo Becerra',
        web: 'https://es.linkedin.com/in/pablo-becerra-l%C3%B3pez',
        sector: 'arte-3d',
        sectorLabel: 'Arte 3D',
        tecnologias: ['3D Modeling', 'ZBrush', 'Blender', 'Character Design'],
        descripcion: 'Artista 3D freelance especializado en character design y modelado para videojuegos y producciones audiovisuales.',
        espacioId: 'despacho-3',
        tamano: 'freelance',
        empleados: 1,
    },
    {
        id: 'murcielagos',
        nombre: 'Murciélagos',
        web: 'https://murcielagosmalaga.com',
        sector: 'videojuegos',
        sectorLabel: 'Videojuegos',
        tecnologias: ['Tabletop Games', 'Board Games', 'Hybrid Games', 'Print & Play'],
        descripcion: 'Estudio creativo especializado en juegos de mesa, juegos híbridos y experiencias lúdicas analógicas-digitales.',
        espacioId: 'go2work',
        tamano: 'startup',
        empleados: 3,
    },
    {
        id: 'naolito',
        nombre: 'Naolito',
        web: 'http://www.naolito.com',
        sector: 'animacion',
        sectorLabel: 'Animación 2D/3D',
        tecnologias: ['Animación 2D', 'After Effects', 'Motion Graphics', 'Ilustración'],
        descripcion: 'Estudio de animación 2D e ilustración con un estilo único, especializado en contenido para marcas y entretenimiento.',
        espacioId: 'coworking-2',
        tamano: 'freelance',
        empleados: 2,
    },
    {
        id: 'novelingo',
        nombre: 'Novelingo',
        web: 'https://www.novelingo.com',
        sector: 'edicion',
        sectorLabel: 'Narrativa Digital',
        tecnologias: ['Narrativa Interactiva', 'Storytelling', 'Ficción Digital', 'Contenidos'],
        descripcion: 'Plataforma de narrativa digital y ficción interactiva. Crea experiencias de lectura inmersivas y ramificadas.',
        espacioId: 'despacho-flex',
        tamano: 'startup',
        empleados: 4,
    },
    {
        id: 'owogame',
        nombre: 'OWO Game',
        web: 'https://owogame.com',
        sector: 'videojuegos',
        sectorLabel: 'Videojuegos',
        tecnologias: ['Haptic Gaming', 'Sensores EMG', 'VR', 'Wearable Tech'],
        descripcion: 'Pioneros en videojuegos hápticos con chalecos sensoriales. Combina EMG, VR y wearables para una experiencia inmersiva única.',
        espacioId: 'go2work',
        tamano: 'startup',
        empleados: 11,
    },
    {
        id: 'prosfy',
        nombre: 'Prosfy',
        web: 'https://prosfy.com',
        sector: 'fintech',
        sectorLabel: 'Tecnología Financiera',
        tecnologias: ['Fintech', 'Data Analytics', 'Deportes', 'Gamificación'],
        descripcion: 'Plataforma fintech con componente social y de gamificación, enfocada en el sector deportivo y lifestyle.',
        espacioId: 'modulo-1',
        tamano: 'pyme',
        empleados: 9,
    },
    {
        id: 'redvelgames',
        nombre: 'Red Vel Games',
        web: 'https://redvelgames.com',
        sector: 'videojuegos',
        sectorLabel: 'Videojuegos',
        tecnologias: ['Unity', 'Mobile Games', 'Multiplayer', 'Backend'],
        descripcion: 'Estudio de videojuegos móviles con fuerte componente multijugador y servicios backend escalables.',
        espacioId: 'despacho-3',
        tamano: 'startup',
        empleados: 6,
    },
    {
        id: 'releevant',
        nombre: 'Releevant',
        web: 'https://www.releevant.com',
        sector: 'ia',
        sectorLabel: 'Inteligencia Artificial',
        tecnologias: ['ML', 'Computer Vision', 'Retail Tech', 'Analytics'],
        descripcion: 'Soluciones de IA y computer vision aplicadas al retail. Reconocimiento visual y analítica avanzada para tiendas.',
        espacioId: 'modulo-2',
        tamano: 'pyme',
        empleados: 14,
    },
    {
        id: 'talestudios',
        nombre: 'Tal Estudios',
        web: 'https://www.talestudios.com',
        sector: 'animacion',
        sectorLabel: 'Animación 3D',
        tecnologias: ['Animación 3D', 'CGI', 'VFX', 'Maya'],
        descripcion: 'Estudio de animación 3D y efectos visuales para series, publicidad y largometrajes.',
        espacioId: 'lab-3d',
        tamano: 'pyme',
        empleados: 18,
    },
    {
        id: 'tindustry',
        nombre: 'Twindustry',
        web: 'https://www.twindustry.net',
        sector: 'industria-4',
        sectorLabel: 'Industria 4.0',
        tecnologias: ['IoT', 'Digital Twin', 'Industry 4.0', 'Predictive Maintenance'],
        descripcion: 'Tecnología para la industria 4.0: IoT, gemelos digitales y mantenimiento predictivo para fábricas inteligentes.',
        espacioId: 'modulo-1',
        tamano: 'pyme',
        empleados: 12,
    },
    {
        id: 'underthebed',
        nombre: 'Under the Bed Games',
        web: 'https://underthebedgames.com',
        sector: 'videojuegos',
        sectorLabel: 'Videojuegos',
        tecnologias: ['Unity', 'Narrative Games', 'Indie', 'Atmospheric Horror'],
        descripcion: 'Estudio indie de juegos narrativos y de terror atmosférico. Especializados en experiencias inmersivas y psicológicas.',
        espacioId: 'go2work',
        tamano: 'startup',
        empleados: 3,
    },
];

// Sectores disponibles (para filtros)
const SECTORES = [
    { id: 'videojuegos', label: 'Videojuegos', color: '#5b8def', icono: 'gamepad-2' },
    { id: 'xr', label: 'Realidad Virtual / XR', color: '#9b6dff', icono: 'vr' },
    { id: 'audio', label: 'Audio y Sonido', color: '#00a88f', icono: 'mic' },
    { id: 'animacion', label: 'Animación', color: '#f39200', icono: 'film' },
    { id: 'produccion-audiovisual', label: 'Producción Audiovisual', color: '#e94e77', icono: 'video' },
    { id: 'arte-digital', label: 'Arte Digital', color: '#ff6b9d', icono: 'palette' },
    { id: 'arte-3d', label: 'Arte 3D', color: '#3ecf8e', icono: 'box' },
    { id: 'ia', label: 'Inteligencia Artificial', color: '#7b61ff', icono: 'brain' },
    { id: 'simulacion', label: 'Simulación', color: '#16a085', icono: 'cog' },
    { id: 'ciberseguridad', label: 'Ciberseguridad', color: '#e74c3c', icono: 'shield' },
    { id: 'marketing', label: 'Marketing Digital', color: '#f39c12', icono: 'megaphone' },
    { id: 'edicion', label: 'Narrativa / Edición', color: '#3498db', icono: 'book-open' },
    { id: 'fintech', label: 'Fintech', color: '#27ae60', icono: 'trending-up' },
    { id: 'industria-4', label: 'Industria 4.0', color: '#8e44ad', icono: 'factory' },
    { id: 'artes-escenicas', label: 'Artes Escénicas', color: '#d35400', icono: 'masks' },
];

// Datos de tarifas y bases (resumidos para info)
const POLO_INFO = {
    nombre: 'Polo Nacional de Contenidos Digitales',
    direccion: 'Avda. Sor Teresa Prat, 15 (Edificio E3, Tabacalera), 29003 Málaga',
    telefono: '+34 952 026 969',
    email: 'hola@polodigital.eu',
    web: 'https://www.polodigital.eu',
    habitantes: 27,
    espacios: 30,
    sectores: SECTORES.length,
};

// Sinergias predefinidas (basadas en investigación + análisis de complementariedades)
const SINERGIAS_PREDEFINIDAS = [
    { empresas: ['forgottenempires', 'krilloud'], razon: 'Forgotten Empires (RTS AAA) necesita audio interactivo premium que Krilloud puede producir.' },
    { empresas: ['forgottenempires', 'talestudios'], razon: 'Forgotten Empires puede externalizar cinemáticas y animaciones 3D al estudio Tal Estudios.' },
    { empresas: ['featlander', 'owogame'], razon: 'Ambos en gaming móvil hiper-casual con haptics: pueden co-desarrollar mecánicas sensoriales.' },
    { empresas: ['featlander', 'krilloud'], razon: 'Juegos hiper-casuales necesitan audio rápido e iterativo: Krilloud puede ser partner.' },
    { empresas: ['cienciavr', 'mickrea'], razon: 'CienciaVR (educación VR) y Mickrea (XR industrial) pueden compartir conocimiento técnico en MR.' },
    { empresas: ['cienciavr', 'lab-vr'], razon: 'CienciaVR puede testear sus experiencias en el equipamiento del Lab. VR del Polo.' },
    { empresas: ['inakin', 'owogame'], razon: 'Ambos en acción multijugador: sinergia en game servers, networking y eSports.' },
    { empresas: ['inone', 'releevant'], razon: 'Ambas en IA aplicada: Inone (consultoría) + Releevant (retail) pueden co-crear soluciones verticales.' },
    { empresas: ['inone', 'bebite'], razon: 'IA (Inone) + Ciberseguridad (Bebite) = oportunidades en sistemas inteligentes seguros.' },
    { empresas: ['eartes', 'naolito'], razon: 'Eartes (ilustración) y Naolito (animación 2D) pueden co-crear contenido visual para campañas.' },
    { empresas: ['eartes', 'pablobecerra'], razon: 'Ambos artistas visuales: colaboraciones en character design y dirección de arte.' },
    { empresas: ['eartes', 'novelingo'], razon: 'Ilustración + narrativa digital = libros interactivos ilustrados.' },
    { empresas: ['heqate', 'lab-video'], razon: 'Heqate puede aprovechar el equipamiento del Lab. Audiovisual del Polo para producciones.' },
    { empresas: ['malagafilmoffice', 'heqate'], razon: 'Málaga Film Office (comisión) + Heqate (productora) = sinergia en rodajes y localizaciones.' },
    { empresas: ['malagafilmoffice', 'gimnasioescenico'], razon: 'Film Commission + Compañía de artes escénicas para Málaga como plató audiovisual.' },
    { empresas: ['mickrea', 'lab-vr'], razon: 'Mickrea es vecino del Lab. VR, ideal para testeo de prototipos y transferencia tecnológica.' },
    { empresas: ['talestudios', 'pablobecerra'], razon: 'Tal Estudios (animación 3D) puede absorber trabajo de modelado 3D que Pablo Becerra externalice.' },
    { empresas: ['talestudios', 'lab-3d'], razon: 'Tal Estudios puede prototipar assets físicos en el Lab. de Impresión 3D para merchandising o props.' },
    { empresas: ['redvelgames', 'featlander'], razon: 'Ambos en gaming móvil: backend compartido, marketing cruzado, knowledge sharing.' },
    { empresas: ['64train', 'murcielagos'], razon: 'Videojuegos narrativos + juegos híbridos: experimentación cruzada en formatos.' },
    { empresas: ['64train', 'novelingo'], razon: 'Narrativa interactiva: Novelingo domina textos, 64Train implementa juegos narrativos.' },
    { empresas: ['underthebed', 'novelingo'], razon: 'Juegos narrativos de terror + plataforma de ficción digital: co-creación de IPs.' },
    { empresas: ['gimnasioescenico', 'mickrea'], razon: 'Teatro inmersivo + XR: nuevos formatos de artes escénicas en realidad mixta.' },
    { empresas: ['prosfy', 'inone'], razon: 'Prosfy (fintech) + Inone (IA): modelos predictivos y analítica para finanzas.' },
    { empresas: ['tindustry', 'releevant'], razon: 'Industria 4.0 + Computer Vision: gemelos digitales con análisis visual avanzado.' },
    { empresas: ['tindustry', 'bebite'], razon: 'IoT industrial + Ciberseguridad: securización de dispositivos conectados.' },
    { empresas: ['ademass', 'bebite'], razon: 'Marketing digital + Ciberseguridad: paquetes completos de presencia digital segura.' },
    { empresas: ['bestridesimulators', 'mickrea'], razon: 'Simuladores de movimiento + Mixed Reality: simuladores más inmersivos.' },
    { empresas: ['bestridesimulators', 'lab-3d'], razon: 'Pueden prototipar piezas y controles físicos en el Lab. de Impresión 3D.' },
    { empresas: ['cookingandpublishing', 'novelingo'], razon: 'Editorial digital + narrativa interactiva: libros de cocina interactivos.' },
    { empresas: ['owogame', 'gimnasioescenico'], razon: 'Haptics + Artes escénicas: performances sensoriales inmersivas.' },
    { empresas: ['inone', 'lab-3d'], razon: 'Inone puede prototipar hardware con IA en el Lab. de Impresión 3D.' },
    { empresas: ['bebite', 'lab-3d'], razon: 'Bebite puede usar el Lab. para prototipar carcasas de hardware de seguridad.' },
    { empresas: ['malagafilmoffice', 'lab-audio'], razon: 'Film Commission + Estudio de Audio: localización de doblajes en Málaga.' },
    { empresas: ['featlander', 'redvelgames'], razon: 'Ambos en Unity + mobile: comparten pipelines y assets reutilizables.' },
];
